/**
 ******************************************************************************
 * @file           : main.c
 * @author        : Juan Francisco Padilla Fuentes <jfpadifu03@gmail.com>
 * @version        : 1.0.0
 * @date           : 2026-02-18
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 * Base project auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * Check copyright and license information in the LICENSE file in the root directory of the project
 *
 ******************************************************************************
 */
#include "stm32c031xx.h"
#include <stdint.h>

/* Alias for PIN5 representing LED pin */
#define LED_PIN		GPIO_ODR_OD5

int main(void)
{
	/* Enable clock access to GPIOA */
	RCC->IOPENR |= RCC_IOPENR_GPIOAEN;
	GPIOA->MODER |= (1U<<10);
	GPIOA->MODER &= ~(1U<<11);

	while(1)
	{
	 /* Set PA5(LED_PIN) high */
	 GPIOA->ODR^= LED_PIN;

	 for(int i=0;i<1000000;i++); /**< Simple delay */
	}
}
