/**
 ******************************************************************************
 * @file           : gopio.h
 * @author        : Juan Francisco Padilla Fuentes <jfpadifu03@gmail.com>
 * @version        : 1.0.0
 * @date           : 2026-02-19
 * @brief          : GPIO header file for LED and Button control
 ******************************************************************************
 * @attention
 * Base project auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * Check copyright and license information in the LICENSE file in the root directory of the project
 *
 ******************************************************************************
 */
#ifndef GPIO_H_
#define GPIO_H_

#include <stdbool.h>
#include <stm32c031xx.h>

void led_init(void);
void led_on(void);
void led_off(void);
void btn_init(void);
bool btn_get_state(void);

#endif /* GPIO_H_ */
