/**
 ******************************************************************************
 * @file           : adc.h
 * @author        : Juan Francisco Padilla Fuentes <jfpadifu03@gmail.com>
 * @version        : 1.0.0
 * @date           : 2026-02-19
 * @brief          : ADC header file
 ******************************************************************************
 * @attention
 * Base project auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * Check copyright and license information in the LICENSE file in the root directory of the project
 *
 ******************************************************************************
 */
#ifndef ADC_H_
#define ADC_H_

#include <stdint.h>
#include <stm32c031xx.h>

void adc1_ch1_init(void);
void adc1_ch1_single_conversion(void);
void adc1_ch1_start_continuous_conversion(void);
uint32_t adc1_ch1_read(void);

#endif /* ADC_H_ */