/**
 ******************************************************************************
 * @file           : systick.h
 * @author         : Juan Francisco Padilla Fuentes <jfpadifu03@gmail.com>
 * @version        : 1.0.0
 * @date           : 2026-02-25
 * @brief          : SysTick timer header file
 ******************************************************************************
 * @attention
 * Base project auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * Check copyright and license information in the LICENSE file in the root 
 * directory of the project
 *
 ******************************************************************************
 */
#ifndef SYSTICK_H_
#define SYSTICK_H_

#include "stm32c031xx.h"

void delay_ms(uint32_t ms);

#endif /* SYSTICK_H_ */
