/**
 ******************************************************************************
 * @file           : uart.h
 * @author        : Juan Francisco Padilla Fuentes <jfpadifu03@gmail.com>
 * @version        : 1.0.0
 * @date           : 2026-02-19
 * @brief          : UART communication header file
 ******************************************************************************
 * @attention
 * Base project auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * Check copyright and license information in the LICENSE file in the root directory of the project
 *
 ******************************************************************************
 */
#ifndef UART_H_
#define UART_H_

#include <stdint.h>
#include <stm32c031xx.h>

void uart_init(void);
void uart_write(uint8_t ch);
uint8_t uart_read(void);
void uart_print(const char *str);


#endif /* UART_H_ */