/**
******************************************************************************
* @file           : timer.h
* @author         : Juan Francisco Padilla Fuentes <jfpadifu03@gmail.com>
* @version        : 1.0.0
* @date           : 2026-02-19
* @brief          : Timer header file
******************************************************************************
* @attention
* Base project auto-generated by STM32CubeIDE for Visual Studio Code Extension
* Check copyright and license information in the LICENSE file in the root directory of the project
*
******************************************************************************
*/
#ifndef INC_TIMER_H_
#define INC_TIMER_H_

#include <stdint.h>
#include <stdbool.h>

#include "stm32c031xx.h"
#include "system_stm32c0xx.h"

void upcounter_timer_start(void);
uint32_t upcounter_timer_stop(void);
bool upcounter_timer_has_elapsed(void);

void downcounter_timer_start(uint32_t reload_value_ms);
void downcounter_timer_stop(void);
bool downcounter_timer_has_elapsed(void);

#endif /* INC_TIMER_H_ */
