/**
 ******************************************************************************
 * @file           : gpio.c
 * @author        : Juan Francisco Padilla Fuentes <jfpadifu03@gmail.com>
 * @version        : 1.0.0
 * @date           : 2026-02-19
 * @brief          : GPIO source file for LED and Button control
 ******************************************************************************
 * @attention
 * Base project auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * Check copyright and license information in the LICENSE file in the root directory of the project
 *
 ******************************************************************************
 */
#include "gpio.h"

void led_init(void)
{
	/* Enable clock access to GPIOA */
	RCC->IOPENR |= RCC_IOPENR_GPIOAEN;
	/* Set PA5 mode to output mode */
	GPIOA->MODER |= (1U << 10);
	GPIOA->MODER &= ~(1U << 11);
}

void led_on(void)
{
	/* Set PA5 */
	GPIOA->ODR |= GPIO_ODR_OD5;
}

void led_off(void)
{
	/* Reset PA5 */
	GPIOA->ODR &= ~GPIO_ODR_OD5;
}

void btn_init(void)
{
	/* Enable clock access to GPIOC */
	RCC->IOPENR |= RCC_IOPENR_GPIOCEN;

	/* Set PC13 mode to input mode */
	GPIOC->MODER &= ~(1U << 26);
	GPIOC->MODER &= ~(1U << 27);
}

bool btn_get_state(void)
{
	 /* Note : BTN is active low and connected to PC13 */
	 if(GPIOC->IDR & GPIO_IDR_ID13)
	 {
		 return false;
	 }
	 else
	 {
		 return true;
	 }
}