/**
 ******************************************************************************
 * @file           : main.c
 * @author        : Juan Francisco Padilla Fuentes <jfpadifu03@gmail.com>
 * @version        : 1.0.0
 * @date           : 2026-02-18
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 * Base project auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * Check copyright and license information in the LICENSE file in the root directory of the project
 *
 ******************************************************************************
 */
#include "gpio.h"

int main(void)
{
	bool btn_state;

	/* Initialize LED */
	led_init();

	/* Initialize Pushbutton */
	btn_init();

	while(1)
	{
		/* Get button State */
		btn_state = btn_get_state();

		if(btn_state)
		{
			led_on();
		}
		else
		{
			led_off();
		}
	}
}