/**
 ******************************************************************************
 * @file           : main.c
 * @author        : Juan Francisco Padilla Fuentes <jfpadifu03@gmail.com>
 * @version        : 1.0.0
 * @date           : 2026-02-18
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 * Base project auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * Check copyright and license information in the LICENSE file in the root directory of the project
 *
 ******************************************************************************
 */
#include "adc.h"
#include "uart.h"

/* Lightweight integer to decimal string (works for 0..99999) */
static void itoa_simple(int val, char *buf)
{
	if (val < 0) { *buf++ = '-'; val = -val; }
	char tmp[10];
	int i = 0;
	do {
		tmp[i++] = '0' + (val % 10);
		val /= 10;
	} while (val);
	while (i--) *buf++ = tmp[i];
	*buf = '\0';
}

int sensor_value;

int main(void)
{
	adc1_ch1_init();
	uart_init();
	uart_print("Simple audio system with adjustable volume ready!\r\n");

	//adc1_ch1_start_continuous_conversion();

	while(1)
	{
		adc1_ch1_single_conversion();
		sensor_value = adc1_ch1_read();

		char num_buf[12];

		uart_print("Sensor value = ");
		itoa_simple(sensor_value, num_buf);
		uart_print(num_buf);
		uart_print("\r\n");

		/* 0 -> 0%, 4095 -> 100% */
		int volume_percentage = sensor_value * 100 / 4095;
		uart_print("Volume = ");
		itoa_simple(volume_percentage, num_buf);
		uart_print(num_buf);
		uart_print("%\r\n\n");
		for (volatile int i = 0; i < 1000000; i++); // ~1 s delay
	}
}
