/**
******************************************************************************
* @file           : main.c
* @author        : Juan Francisco Padilla Fuentes <jfpadifu03@gmail.com>
* @version        : 1.0.0
* @date           : 2026-02-26
* @brief          : Main program body
******************************************************************************
* @attention
* Base project auto-generated by STM32CubeIDE for Visual Studio Code Extension
* Check copyright and license information in the LICENSE file in the root directory of the project
*
******************************************************************************
*/
#include <stdbool.h>
#include <stdio.h>

#include "gpio.h"
#include "uart.h"
#include "timer.h"

#define DELAY_MS	10000U

static void uint_to_str(uint32_t val, char *buf);

int main(void)
{
    bool led_status = false;
    uint32_t reaction_time = 0;

	led_init();
    btn_init();
    uart_init();

    uart_print("Formula 1 Reaction-Time Training System starts!\r\n");
    downcounter_timer_start(DELAY_MS);

    while(1) {
        // Check if the downcounter timer has elapsed, start the upcounter timer and turn on the LED
        if(downcounter_timer_has_elapsed()) {
            downcounter_timer_stop();
            led_on();
            upcounter_timer_start();
            led_status = true;
        }

        // Check if the upcounter timer has elapsed, stop the timer, turn off the LED and print a message. Restart the game.
        if (upcounter_timer_has_elapsed()) {
            upcounter_timer_stop();
            led_off();
            led_status = false;
            uart_print("Time's up! You were too slow, try again!\r\n");
            downcounter_timer_start(DELAY_MS);
        }
        
        // Check if the button is pressed, if so, check if the LED is on. 
        // If the LED is on, stop the upcounter timer, turn off the LED and print the reaction time. Restart the game. 
        // If the LED is off, print a message and restart the game.
        if(detect_btn_pressed()) {
            if (led_status) {
                reaction_time = upcounter_timer_stop();
                led_off();
                led_status = false;
                uart_print("Congratulations! Your reaction time was: ");
                char buffer[10];
                uint_to_str(reaction_time, buffer);
                uart_print(buffer);
                uart_print(" us. Restarting the game!\r\n");
                downcounter_timer_start(DELAY_MS);
            } else {
                uart_print("Too soon!\r\n Wait for the LED to turn on before pressing the button.\r\n Try again!\r\n");
                downcounter_timer_start(DELAY_MS);
            }
        }
    }
}

/**
 * @brief  Convert an unsigned integer to a decimal string.
 * @param  val   Value to convert
 * @param  buf   Output buffer (must be at least 11 bytes)
 */
static void uint_to_str(uint32_t val, char *buf)
{
	char tmp[10];
	int i = 0;

	if (val == 0)
	{
		buf[0] = '0';
		buf[1] = '\0';
		return;
	}
	while (val > 0)
	{
		tmp[i++] = '0' + (val % 10);
		val /= 10;
	}
	int j = 0;
	while (i > 0)
	{
		buf[j++] = tmp[--i];
	}
	buf[j] = '\0';
}
