/**
******************************************************************************
* @file           : timer.c
* @author         : Juan Francisco Padilla Fuentes <jfpadifu03@gmail.com>
* @version        : 1.0.0
* @date           : 2026-02-19
* @brief          : Timer source file
******************************************************************************
* @attention
* Base project auto-generated by STM32CubeIDE for Visual Studio Code Extension
* Check copyright and license information in the LICENSE file in the root directory of the project
*
******************************************************************************
*/
#include "timer.h"
#include "stm32c031xx.h"
#include <stdint.h>

/**
 * @brief Upcounter timer start function. 
 * Configures TIM16 to count up with 10 us resolution and a timeout of 500 ms.
 * This function enables the timer and starts counting immediately.
 *
 * @return None
 */
void upcounter_timer_start(void)
{
    SystemCoreClockUpdate();  // Update SystemCoreClock variable
    RCC->APBENR2 |= RCC_APBENR2_TIM16EN;  // Enable clock for TIM16
    TIM16->CR1 = 0;  // Stop timer, clear config
    TIM16->PSC = (uint16_t)(SystemCoreClock / 100000 - 1);  // 10 us resolution (100 kHz tick)
    TIM16->ARR = (uint16_t)(50000 - 1);  // 500 ms timeout at 100 kHz (50,000 ticks fits in 16-bit)
    TIM16->EGR = TIM_EGR_UG;  // Generate update event to load PSC shadow register
    TIM16->SR  = 0;  // Clear UIF set by the update event
    TIM16->CR1 = TIM_CR1_CEN;  // Start the timer
}

/**
 * @brief Upcounter timer stop function. 
 * Stops TIM16 and resets the counter value to zero.
 *
 * @return The elapsed time in microseconds since the timer was started.
 */
uint32_t upcounter_timer_stop(void)
{
    uint32_t count = TIM16->CNT;  // Read the current counter value
    TIM16->CR1 &= ~TIM_CR1_CEN;  // Stop the timer
    TIM16->CNT = 0;  // Reset counter
    TIM16->SR &= ~TIM_SR_UIF;  // Clear update interrupt flag
    return count * 10;  // Convert ticks (10 us each) to microseconds
}

/**
 * @brief Check if the upcounter timer has elapsed.
 *
 * @return true if the timer has elapsed, false otherwise
 */
bool upcounter_timer_has_elapsed(void)
{
    bool ret = false;
    
    if (TIM16->SR & TIM_SR_UIF) {
        ret = true;
        TIM16->SR &= ~TIM_SR_UIF;  // Clear update interrupt flag
    }

    return ret;
}

/**
 * @brief Downcounter timer start function.
 * Configures TIM3 to count down with millisecond resolution and a specified period.
 *
 * @param reload_value_ms The auto-reload value in milliseconds.
 *
 * @return None
 */
void downcounter_timer_start(uint32_t reload_value_ms)
{
    SystemCoreClockUpdate();  // Update SystemCoreClock variable
    RCC->APBENR1 |= RCC_APBENR1_TIM3EN;  // Enable clock for TIM3
    TIM3->CR1 = 0;  // Stop timer, clear config
    TIM3->PSC = (uint16_t)(SystemCoreClock / 1000 - 1);  // Set prescaler to millisecond resolution (1 kHz)
    if (reload_value_ms == 0) reload_value_ms = 1; // Prevent ARR=0 (counter blocked)
    TIM3->ARR = (uint16_t)(reload_value_ms - 1);  // Set auto-reload for specified milliseconds
    TIM3->CR1 = TIM_CR1_DIR;  // Set downcounting mode BEFORE update event
    TIM3->EGR = TIM_EGR_UG;  // Generate update event to load PSC/ARR and set CNT = ARR
    TIM3->SR  = 0;  // Clear UIF set by the update event
    TIM3->CR1 |= TIM_CR1_CEN;  // Start the timer
}

/**
 * @brief Downcounter timer stop function.
 * Stops TIM3 and resets the counter value to zero.
 *
 * @return None
 */
 void downcounter_timer_stop(void)
{
    TIM3->CR1 &= ~TIM_CR1_CEN;  // Stop the timer
    TIM3->CNT = 0;  // Reset counter
    TIM3->SR &= ~TIM_SR_UIF;  // Clear update interrupt flag
}

/**
 * @brief Check if the downcounter timer has elapsed.
 *
 * @return true if the timer has elapsed, false otherwise
 */
bool downcounter_timer_has_elapsed(void)
{
    bool ret = false;
    
    if (TIM3->SR & TIM_SR_UIF) {
        ret = true;
        TIM3->SR &= ~TIM_SR_UIF;  // Clear update interrupt flag
    }

    return ret;
}
