/**
******************************************************************************
* @file           : uart.c
* @author        : Juan Francisco Padilla Fuentes <jfpadifu03@gmail.com>
* @version        : 1.0.0
* @date           : 2026-02-19
* @brief          : UART communication source file
******************************************************************************
* @attention
* Base project auto-generated by STM32CubeIDE for Visual Studio Code Extension
* Check copyright and license information in the LICENSE file in the root directory of the project
*
******************************************************************************
*/
#include "uart.h"

#define UART2_BAUDRATE		115200	// Baud rate for UART2 communication

/**
 * @brief Initialize UART2 for communication.
 *
 * This function configures the GPIO pins for UART2 (PA2 for TX and PA3 for RX), sets the baud rate, and enables the UART module.
 *
 * @return None
 */
void uart_init(void)
{
	/* Enable clock access to GPIOA */
	RCC->IOPENR |= RCC_IOPENR_GPIOAEN;

	/* Set the mode of PA2 and PA3 to alternate function mode */
	GPIOA->MODER &= ~(3U << 4);  // clear PA2 mode field
	GPIOA->MODER |=  (2U << 4);  // set alternate function (0b10)
	GPIOA->MODER &= ~(3U << 6);  // clear PA3 mode field
	GPIOA->MODER |=  (2U << 6);  // set alternate function (0b10)

	/* Set alternate function type to AF1(UART2_TX) */
	GPIOA->AFR[0] &= ~(0xFU << 8);   // clear PA2 AF field
	GPIOA->AFR[0] |=  (0x1U << 8);   // set AF1

	/* Set alternate function type to AF1(UART2_RX) */
	GPIOA->AFR[0] &= ~(0xFU << 12);   // clear PA3 AF field
	GPIOA->AFR[0] |=  (0x1U << 12);   // set AF1

	/* Enable clock access to UART2 */
	RCC->APBENR1 |= RCC_APBENR1_USART2EN;

	/* Configure UART baudrate */
	SystemCoreClockUpdate();
	uint32_t apb_shift = APBPrescTable[(RCC->CFGR & RCC_CFGR_PPRE) >> RCC_CFGR_PPRE_Pos];
	uint32_t pclk1 = SystemCoreClock >> apb_shift;
	USART2->BRR = pclk1 / UART2_BAUDRATE;

	/* Configure transfer direction */
	USART2->CR1 = USART_CR1_TE | USART_CR1_RE;

	/* Enable UART Module */
	USART2->CR1 |= USART_CR1_UE;
}

/**
 * @brief Send a single byte of data over UART.
 *
 * This function waits until the transmit data register is empty and then writes the byte to be transmitted.
 *
 * @param ch The byte of data to send over UART
 *
 * @return None
 */
void uart_write(uint8_t ch)
{
	 /* Make sure transmit data register is empty */
	while (!(USART2->ISR & USART_ISR_TXE_TXFNF));

	 /* Write to transmit data register */
	USART2->TDR = ch;
}

/**
 * @brief Read a byte of data from UART.
 *
 * This function waits until data is received and then reads it from the receive data register.
 *
 * @return The byte of data received over UART
 */
uint8_t uart_read(void)
{
    /* Wait until data is received */
	while (!(USART2->ISR & USART_ISR_RXNE_RXFNE));

    /* Read from Receive Data Register */
	return (uint8_t)(USART2->RDR & 0xFF);
}

/**
 * @brief Send a null-terminated string over UART.
 *
 * This function iterates through each character in the string and sends it using uart_write.
 *
 * @param str The null-terminated string to send
 *
 * @return None
 */
void uart_print(const char *str)
{
    while (*str) uart_write((uint8_t)*str++);
}

