/**
******************************************************************************
* @file           : gpio.c
* @author        : Juan Francisco Padilla Fuentes <jfpadifu03@gmail.com>
* @version        : 1.0.0
* @date           : 2026-02-19
* @brief          : GPIO source file for LED and Button control
******************************************************************************
* @attention
* Base project auto-generated by STM32CubeIDE for Visual Studio Code Extension
* Check copyright and license information in the LICENSE file in the root directory of the project
*
******************************************************************************
*/
#include "gpio.h"

/**
 * @brief Initialize the LED GPIO pin (PA5) as output.
 *
 * This function enables the clock for GPIOA and configures PA5 as a general-purpose output pin.
 *
 * @return None
 */
void led_init(void)
{
	/* Enable clock access to GPIOA */
	RCC->IOPENR |= RCC_IOPENR_GPIOAEN;
	/* Set PA5 mode to output mode */
	GPIOA->MODER |= (1U << 10);
	GPIOA->MODER &= ~(1U << 11);
}

/**
 * @brief Turn on the LED connected to PA5.
 *
 * This function sets the output data register bit corresponding to PA5, effectively turning on the LED.
 *
 * @return None
 */
void led_on(void)
{
	/* Set PA5 */
	GPIOA->ODR |= GPIO_ODR_OD5;
}

/**
 * @brief Turn off the LED connected to PA5.
 *
 * This function clears the output data register bit corresponding to PA5, effectively turning off the LED.
 *
 * @return None
 */
void led_off(void)
{
	/* Reset PA5 */
	GPIOA->ODR &= ~GPIO_ODR_OD5;
}

/**
 * @brief Toggle the state of the LED connected to PA5.
 * If the LED is currently on, it will be turned off, and if it is currently off, it will be turned on.
 *
 * @return None
 */
void led_toggle(void)
{
	/* Toggle PA5 */
	GPIOA->ODR ^= GPIO_ODR_OD5;
}

/**
 * @brief Initialize the button GPIO pin (PC13) as input.
 * The button is active-low, so it will read LOW when pressed and HIGH when not pressed.
 *
 * @return None
 */
void btn_init(void)
{
	/* Enable clock access to GPIOC */
	RCC->IOPENR |= RCC_IOPENR_GPIOCEN;

	/* Set PC13 mode to input mode */
	GPIOC->MODER &= ~(1U << 26);
	GPIOC->MODER &= ~(1U << 27);

    
}

/**
 * @brief Initialize the button GPIO pin (PC13) as input with interrupt.
 *
 * This function configures the button pin as input and sets up the EXTI interrupt
 * for detecting button presses.
 *
 * @return None
 */
void btn_irq_init(void)
{
    /* Disable interrupts while configuring the button */
    __disable_irq();

    /* Configure EXTI line 13 for PC13 (falling edge = button press, active-low) */
    EXTI->EXTICR[3] &= ~EXTI_EXTICR4_EXTI13;                    /* Clear EXTI13 mux bits          */
    EXTI->EXTICR[3] |= EXTI_EXTICR4_EXTI13_1;                   /* Map EXTI13 to Port C (PC = 2)  */
    EXTI->FTSR1     |= EXTI_FTSR1_FT13;                         /* Trigger on falling edge         */
    EXTI->IMR1      |= EXTI_IMR1_IM13;                          /* Unmask EXTI13 interrupt          */
    NVIC_EnableIRQ(EXTI4_15_IRQn);                        /* Enable EXTI4-15 IRQ in NVIC     */

    /* Enable interrupts after configuration */
    __enable_irq();
}

/**
 * @brief Get the current state of the button.
 * 
 * @return true if the button is pressed, false otherwise
 */
bool btn_get_state(void)
{
	/* BTN is active-low on PC13: pin HIGH = not pressed, pin LOW = pressed */
	return !(GPIOC->IDR & GPIO_IDR_ID13);
}

/**
 * @brief Detect button release event (falling edge).
 *
 * This function detects when the button transitions from a pressed state to a released state.
 * It uses a static variable to keep track of the previous button state and compares it with the current state.
 *
 * @return true if a button release event is detected, false otherwise
 */
bool detect_btn_released(void)
{
    static bool btn_prev = false;

    bool ret = false;
    bool btn_now = btn_get_state();

    /* Detect release edge: was pressed, now released */
    if (btn_prev && !btn_now)
    {
        ret = true;
    }

    btn_prev = btn_now;
    return ret;
}

/**
 * @brief Detect button press event (rising edge).
 *
 * This function detects when the button transitions from a released state to a pressed state.
 * It uses a static variable to keep track of the previous button state and compares it with the current state.
 *
 * @return true if a button press event is detected, false otherwise
 */
bool detect_btn_pressed(void)
{
    static bool btn_prev = false;

    bool ret = false;
    bool btn_now = btn_get_state();

    /* Detect press edge: was released, now pressed */
    if (!btn_prev && btn_now)
    {
        ret = true;
    }

    btn_prev = btn_now;
    return ret;
}
