/**
******************************************************************************
* @file           : main.c
* @author        : Juan Francisco Padilla Fuentes <jfpadifu03@gmail.com>
* @version        : 1.0.0
* @date           : 2026-02-26
* @brief          : Main program body
******************************************************************************
* @attention
* Base project auto-generated by STM32CubeIDE for Visual Studio Code Extension
* Check copyright and license information in the LICENSE file in the root directory of the project
*
******************************************************************************
*/
#include <stdbool.h>
#include <stdio.h>

#include "gpio.h"
#include "stm32c031xx.h"
#include "systick.h"
#include "uart.h"
#include "timer.h"

#define DELAY_MS	10000U

static volatile bool button_pressed_flag = false;
static volatile bool debounce_flag = false;

void EXTI4_15_IRQHandler(void);
void TIM3_IRQHandler(void);

int main(void)
{
    uint8_t mode = 0;

	led_init();
    btn_init();
	btn_irq_init();
    uart_init();
    

    uart_print("Medical Device Menu Navigation setup :D!\r\n");
    uart_print("Doing some medical stuff... bip bop bip\r\n");

    while(1) {
        switch (mode) {
            case 0:
                uart_print("Mode 1: Displaying patient data...\r\n");
                led_toggle();
                delay_ms(1000);
                led_toggle();
                delay_ms(1000);
                break;
            case 1:
                uart_print("Mode 2: Adjusting device settings...\r\n");
                led_toggle();
                delay_ms(500);
                led_toggle();
                delay_ms(500);
                break;
            case 2:
                uart_print("Mode 3: Running diagnostics...\r\n");
                led_toggle();
                delay_ms(200);
                led_toggle();
                delay_ms(200);
                break;
        }

		if (button_pressed_flag && debounce_flag)
		{
			button_pressed_flag = false; // Clear the flag for the next press
			debounce_flag = false; // Clear the debounce flag
			uart_print("Next button pressed! :D\r\n");
            mode = (mode + 1) % 3; // Cycle through 3 modes (0, 1, 2)
		}
	}
}

/**
 * @brief EXTI4-15 interrupt handler (covers PC13 button press).
 *
 * On the STM32C0 (Cortex-M0+), EXTI lines 4-15 share a single IRQ vector.
 * This handler checks if the interrupt came from line 13 (button) and toggles the LED.
 */
void EXTI4_15_IRQHandler(void)
{
    if ((EXTI->FPR1 & EXTI_FPR1_FPIF13))   /* Falling-edge pending on line 13 and debounce not active */
    {
        EXTI->FPR1 = EXTI_FPR1_FPIF13;		/* Clear flag (write-1-to-clear)    */
        if (!button_pressed_flag) {	
            button_pressed_flag = true;		/* Set flag to indicate button press */
            downcounter_timer_start(80);		/* Start downcounter timer for 80 ms */
            downcounter_timer_enable_irq();    /* Enable timer interrupt to handle debounce timing */
            uart_print("PC13 Interrupt detected! :D\r\n"); /* Debug uart print, indicates debounce period has ended for educational purposes but in a professional code it should be deleted */
        }
    }
}

/**
 * @brief TIM3 interrupt handler.
 *
 * This handler is called when the TIM3 update interrupt occurs, indicating that the downcounter timer has elapsed.
 * It clears the interrupt flag, sets the debounce flag, and stops the timer to prevent further interrupts until the next button press.
 */
void TIM3_IRQHandler(void)
{
	if (TIM3->SR & TIM_SR_UIF)  	/* Check if update interrupt flag is set */
	{
		TIM3->SR &= ~TIM_SR_UIF;  	/* Clear the update interrupt flag */
		debounce_flag = true;  		/* Set debounce flag to indicate timer has elapsed */
		downcounter_timer_stop();  		/* Stop the timer to prevent further interrupts until next button press */
		uart_print("Debounce finished! :D\r\n");	/* Debug uart print, indicates debounce period has ended for educational purposes but in a professional code it should be deleted */
	}
}
